using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MkDocsDatabaseGenerator.ViewModel
{
    public static class Constants
    {
        public const int MaxDirectoryCreationTry = 3;
        public const string PlantUmlStart = "@startuml";
        public const string PlantUmlTheme = "!theme materia-outline";
        public const string PlantUmlOrthoParameter = "skinparam linetype ortho";
        public const string PlantUmlBaseStyle = "!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu";
        public const string PlantUmlEnd = "@enduml";

        public const string AutoGeneratedStartFileName = "AutoGenerated_";
        public const string CustomFolderName = "Custom";
        public const string CustomStartFileName = "Custom_";
        public const string JavaJdkInstallationFolderEnvironnementVariable = "JAVA_HOME";
        public const string OlderFolderName = "Older";
        public const int PlantUmlMaxRenderingTimeMillisecond = 2 * 60 * 1000;
        public const int PlantUmlMaxRenderingTimeSecond = 2 * 60;
        public const string PlantUmlPolyLineParameter = "skinparam linetype polyline";
        public const string TableAutoGeneratedFolderName = "Table";

    }
}
